openapi: 3.2.0
info:
  version: 20.14.1
  title: Symphony Login Idm API
  description: For bots and other on-premise processes to authenticate.
tags:
- name: Idm
paths:
  /idm/tokens:
    post:
      summary: Symphony Returns a valid OAuth2 access token from a given session token to be…
      parameters:
      - name: sessionToken
        description: User session authentication token
        in: header
        required: true
        schema:
          type: string
      - name: scope
        description: 'Optional field used to get access with specific entitlements, use space separated list to define more that one

          '
        in: query
        required: false
        schema:
          type: string
      tags:
      - Idm
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtToken'
        '401':
          description: Client is unauthorized to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden to access this endpoint .
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: postIdmTokens
      x-operation-id-source: derived
  /idm/keys:
    get:
      summary: Symphony Returns the Common Access Token (JWT) Public Keys as a JWKS
      x-since: 20.14
      description: This is a public endpoint, no authentication is required. The JWKS can be used to verify JWT issued by the idm/tokens endpoint. Since SBE 20.14.
      tags:
      - Idm
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jwks'
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: getIdmKeys
      x-operation-id-source: derived
components:
  schemas:
    Jwks:
      type: object
      properties:
        keys:
          type: array
          items:
            $ref: '#/components/schemas/JwksEntry'
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    JwksEntry:
      type: object
      description: A JWK object as defined in https://datatracker.ietf.org/doc/html/rfc7517#section-4.
      additionalProperties:
        type: string
    JwtToken:
      type: object
      properties:
        token_type:
          type: string
          description: Type of token, string "Bearer"
        expires_in:
          type: integer
          format: int64
          description: Duration of time the access token is granted for in seconds
        access_token:
          type: string
          description: 'A JWT containing the caller''s username or application, an expiration date and a set of entitlements related to the

            specified scope, signed by the caller''s private key.

            '
