openapi: 3.2.0
info:
  version: 20.14.1
  title: Symphony Authenticator App API
  description: For bots and other on-premise processes to authenticate.
tags:
- name: App
paths:
  /v1/app/pod/certificate:
    get:
      summary: Symphony Retrieve the certificate that can be use to validate the JWT token…
      tags:
      - App
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PodCertificate'
        '401':
          description: Client is unauthorized to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: getV1AppPodCertificate
      x-operation-id-source: derived
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    PodCertificate:
      type: object
      properties:
        certificate:
          description: Certificate in PEM format
          type: string
