openapi: 3.2.0
info:
  title: Symphony Community Connect Onboarding API
  description: Community Connect public API
  version: 1.3.0
security:
- JwtAuth: []
- ApiKeyAuth: []
tags:
- name: Onboarding
paths:
  /v1/onboarding/tenant:
    get:
      tags:
      - Onboarding
      security:
      - ApiKeyAuth: []
      summary: Symphony Get User's Pod and Availability for Onboarding
      operationId: getUserOnboardingAvailability
      parameters:
      - name: email
        in: query
        schema:
          type: string
        required: true
        description: The user email
        example: user@companyDomain.com
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOnboardingAvaibilityResponse'
              example: Company is already on Symphony but user needs access
        '400':
          description: Something was wrong about the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    UserOnboardingAvaibilityResponse:
      allOf:
      - $ref: '#/components/schemas/ApiInfo'
      - type: object
        properties:
          podUrl:
            type: string
            example: ces4-dev.symphony.com
    ApiInfo:
      type: object
      properties:
        code:
          type: string
          description: info code
        message:
          type: string
          description: Human readable details about the information the api is returning
        details:
          description: Full details about info
          type: object
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: error code
        message:
          type: string
          description: Human readable details about the error
        details:
          description: Full details about error, usefull for 400
          type: object
  securitySchemes:
    JwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: ExtApp JWT
    ApiKeyAuth:
      type: apiKey
      in: query
      name: token
    CommonJwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Common JWT
