openapi: 3.2.0
info:
  title: Symphony Agent Util API
  description: 'This document refers to Symphony API calls to send and receive messages

    and content.'
  version: 22.9.1
servers:
- url: /
tags:
- name: Util
paths:
  /v1/util/echo:
    post:
      tags:
      - Util
      summary: Symphony Test Endpoint, Returns Input
      parameters:
      - name: sessionToken
        in: header
        description: Session authentication token.
        required: true
        schema:
          type: string
      - name: keyManagerToken
        in: header
        description: Key Manager authentication token.
        required: true
        schema:
          type: string
      requestBody:
        description: Message in plain text
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimpleMessage'
        required: true
      responses:
        '200':
          description: Message sent.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleMessage'
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 'Unauthorized: Session tokens invalid.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: echoInput
      operationId: postV1UtilEcho
      x-operation-id-source: derived
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    SimpleMessage:
      type: object
      properties:
        message:
          type: string
      description: A string wrapped in a JSON object.
