openapi: 3.0.1
info:
  title: Symphony Agent Add Privileged User API
  description: 'This document refers to Symphony API calls to send and receive messages

    and content. They need the on-premise Agent installed to perform

    decryption/encryption of content.


    - sessionToken and keyManagerToken can be obtained by calling the

    authenticationAPI on the symphony back end and the key manager

    respectively. Refer to the methods described in authenticatorAPI.yaml.

    - Actions are defined to be atomic, ie will succeed in their entirety

    or fail and have changed nothing.

    - If it returns a 40X status then it will have sent no message to any

    stream even if a request to some subset of the requested streams

    would have succeeded.

    - If this contract cannot be met for any reason then this is an error

    and the response code will be 50X.

    - MessageML is a markup language for messages. See reference here:

    https://rest-api.symphony.com/docs/messagemlv2

    - **Real Time Events**: The following events are returned when reading

    from a real time messages and events stream ("datafeed"). These

    events will be returned for datafeeds created with the v5 endpoints.

    To know more about the endpoints, refer to Create Messages/Events

    Stream and Read Messages/Events Stream. Unless otherwise specified,

    all events were added in 1.46.

    '
  version: 22.9.1
servers:
- url: /
tags:
- name: Privileged User
paths:
  /v1/audittrail/privilegeduser:
    get:
      tags:
      - Privileged User
      summary: Get a list of  actions performed by a privileged account acting as privileged user given a period of time.
      description: Get a list of actions performed by a privileged account acting as privileged user given a period of time.
      parameters:
      - name: sessionToken
        in: header
        description: Session authentication token.
        required: true
        schema:
          type: string
      - name: keyManagerToken
        in: header
        description: Key Manager authentication token.
        required: true
        schema:
          type: string
      - name: startTimestamp
        in: query
        description: Start timestamp in unix timestamp in millseconds.
        required: true
        schema:
          type: integer
          format: int64
      - name: endTimestamp
        in: query
        description: End timestamp in unix timestamp in millseconds. If not specified, it assumes to be current time.
        schema:
          type: integer
          format: int64
      - name: before
        in: query
        description: Return results from an opaque before cursor value as presented via a response cursor.
        schema:
          type: string
      - name: after
        in: query
        description: Return results from an opaque after cursor value as presented via a response cursor.
        schema:
          type: string
      - name: limit
        in: query
        description: 'Max No. of violations to return. If no value is provided, 50 is the default.

          Some maximums for limit may be enforced for performance reasons.

          The maximum supported value is 500.

          '
        schema:
          type: integer
      - name: initiatorId
        in: query
        description: If present, only the initiator with this initiator <user id> will be returned.
        schema:
          type: integer
          format: int64
      - name: role
        in: query
        description: 'If present, only the audit trail initiated by s user with privileged role acting as

          privileged user will be returned.

          Privileged eliglible roles:

          User Provisioning (USER_PROVISIONING),

          Content Management (CONTENT_MANAGEMENT),

          Expression Filter Policy Management (EF_POLICY_MANAGEMENT),

          SCO (SUPER_COMPLIANCE_OFFICER),

          CO (COMPLIANCE_OFFICER),

          Super admin (SUPER_ADMINISTRATOR),

          Admin (ADMINISTRATOR),

          L1 (L1_SUPPORT),

          L2 (L2_SUPPORT),

          Scope Manager (SCOPE_MANAGEMENT)

          '
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1AuditTrailInitiatorList'
        '204':
          description: No Messages.
          content: {}
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 'Unauthorized: Session tokens invalid.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    V1AuditTrailInitiatorResponse:
      type: object
      properties:
        action:
          type: string
          description: The audit trail action that has peformed
        actionName:
          type: string
          description: The audit trail action name that has peformed
        timestamp:
          type: string
          description: The timestamp when the action has occurred
        initiatorId:
          type: string
          description: The user's id that has performed the action
        initiatorUsername:
          type: string
          description: The username that has performed the action
        initiatorEmailAddress:
          type: string
          description: The user's e-mail address that has performed the action
      description: 'Audit Trail Initiator object response.

        The attributes may vary according to the action.

        There are different types of action and each action could have specific attributes.

        '
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Pagination:
      required:
      - cursors
      type: object
      properties:
        cursors:
          type: object
          properties:
            before:
              type: string
              description: 'This is the opaque url-safe string that points to the start of the page of data

                that has been returned.

                '
              example: MTAxNTExOTQ1MjAwNzI5NDE=
            after:
              type: string
              description: 'This is the opaque url-safe string that points to the end of the page of data

                that has been returned.

                '
              example: NDMyNzQyODI3OTQw
        previous:
          type: string
          description: 'API endpoint that will return the previous page of data. If not included, this is

            the first page of data.

            '
          example: https://tenantapi.d.isym.io/v1/tenantinfo?limit=25&before=MTAxNTExOTQ1MjAwNzI5NDE=
        next:
          type: string
          description: 'API endpoint that will return the next page of data. If not included, this is the

            last page of data. Due to how pagination works with visibility and privacy, it is

            possible that a page may be empty but contain a ''next'' paging link. Stop paging when

            the ''next'' link no longer appears.

            '
          example: https://tenantapi.d.isym.io/v1/tenantinfo?limit=25&after=NDMyNzQyODI3OTQw
    V1AuditTrailInitiatorList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/V1AuditTrailInitiatorResponse'
        pagination:
          $ref: '#/components/schemas/Pagination'
