openapi: 3.2.0
info:
  version: 20.14.1
  title: Symphony Authenticator Logout API
  description: For bots and other on-premise processes to authenticate.
tags:
- name: Logout
paths:
  /v1/logout:
    post:
      summary: Symphony Logout
      description: Logout a users session.
      parameters:
      - name: sessionToken
        description: the session token to logout.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Logout
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 'Forbidden: Certificate authentication is not allowed for the requested user.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: postV1Logout
      x-operation-id-source: derived
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
